### ISSUE TITLE
rotation bust

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/flopy#161]
Just realized that the rotation in `spatialReference` is actually positive clockwise, not positive counterclockwise like PEST (and the docstrings).  So the question is do we change the code so that it is in sync with PEST or change the docstring (and add a note about this difference).  I'm inclined to change the code so that `flopy` is the same as PEST but this will break older scripts.  

Does anyone have any objections? or even care?

**Comment by mbakker7** [comment]
Any idea on how many people will have actually used this?

Maybe add a deprecation Warning that shows on the screen that the behavior
has changed as of immediate to comply with the doc string and PEST?

Mark

**Comment by aleaf** [comment]
I agree with Mark's comment. It will break some of my scripts, but nothing that isn't easy to fix. FYI, I checked the [OGW archiving instructions](http://water.usgs.gov/ogw/policy/gw-model/modelers-setup.html) and they don't say anything about what direction the rotation should be in.

**Comment by jtwhite79** [comment]
Done - added warnings if ``rotation != 0.0``.  But...of course it can't be that easy - t31_test.py ``test_get_destination_data()`` is failing.  Looks like there are some "known" MODPATH results using the old rotation scheme, which is now broken.  I commented out the failing assertions.  

Andy - can you look at this?

**Comment by aleaf** [comment]
oh bummer. Will do.

**Comment by jtwhite79** [comment]
Thanks Andy!

**Comment by langevin-usgs** [comment]
Andy, this is still broken.  If you run the flopy3_MapExample notebook, you'll see that it is rotating around the wrong point.  The default should be the upper left corner as the rotation point.  And even if you specify xul and yul in map constuctor, I'm not sure things are working correctly.

![image](https://cloud.githubusercontent.com/assets/3372403/19351479/02caccb8-912a-11e6-9287-1e77fcb8705f.png)

**Comment by aleaf** [comment]
Chris, I did have the sign flipped around in the conversion between xll and xul (fixed [here]( https://github.com/aleaf/flopy/commit/a11f51806acaabf47f105229cc23713bb8f64c1c)). `test_rotation()` should demonstrate that `SpatialReference` doesn't care about the rotation point.  Regardless of whether the ul or ll corners are supplied, the real corner of the grid will be at those points. I think the map constructor is simply showing the map in model coordinates (without any offset; same as the global coordinates output by modpath). Do we want an option to plot in real world coordinates instead?

**Comment by aleaf** [comment]
is there any reason for this code in `ModelMap.__init__`?
```python
# model map override spatial reference settings
        if xul is not None:
            self.sr.xul = xul
        if yul is not None:
            self.sr.yul = yul
        if rotation is not None:
            self.sr.rotation = rotation
```
seems like it might be easier to just call `SpatialReference.set_spatialreference()`. Right now the the xll and yll attributes are not getting set.

**Comment by langevin-usgs** [comment]
Andy, can you try adding a call to SpatialReference.set_spatialreference().  I think that would be easiest.  We definitely want modelmap to show things in real coordinates (not model coordinates).
